import { Box, Container, Flex, Heading, Text } from "@chakra-ui/react";
import { serialize } from "next-mdx-remote/serialize";
import Head from "next/head";
import React from "react";
import Markdown from "../components/Markdown";
import { loadMarkdownFile } from "../loader";

const Header = () => {
  return (
    <>
      <Text
        fontSize={[12, 24]}
        textShadow="3px 1px 15px"
        textAlign="justify"
        textTransform="uppercase"
      >
        Bonjour tout le monde, je m'appelle Finaritra Andrianiaina
      </Text>
      <Heading
        size={"xl"}
        as="h1"
        textTransform="uppercase"
        textAlign="justify"
      >
        Je suis passionné de programmation 💻, de jeux vidéos 🎮 et de voyage
        🏃‍♂⛺.
      </Heading>
      <Text fontSize={["sm", "md"]} textAlign="center" pt={2}>
        Vous êtes sur mon site web personnel construit avec nextjs.
      </Text>
    </>
  );
};

const Home = (props: any) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        as="header"
        height="calc( 100vh - 70px )"
        flexDirection="column"
        alignItems="center"
        justifyContent="space-around"
      >
        <Box width={["100%", "50%"]} px={[5, 0]}>
          <Header />
        </Box>
      </Flex>
      <Container>
        <Markdown md={props.introduction} />
      </Container>
    </>
  );
};

export const getStaticProps = async () => {
  const { content } = await loadMarkdownFile("introduction.mdx");
  const introduction = await serialize(content);
  return { props: { introduction } };
};

export default Home;
