import {
  Box,
  Container,
  Divider,
  Flex,
  Heading,
  HStack,
  Text,
} from "@chakra-ui/react";
import { serialize } from "next-mdx-remote/serialize";
import Head from "next/head";
import React from "react";
import { useEffect } from "react";
import { PostData } from "../blog.type";
import BlogCard from "../components/BlogCard";
import Markdown from "../components/Markdown";
import Profile from "../components/Profile";
import { loadBlogPosts, loadMarkdownFile } from "../loader";
import { createScript } from "../createScript";

const Header = () => {
  return (
    <>
      <Text
        fontSize={[12, 24]}
        textShadow="3px 1px 15px"
        textAlign="justify"
        textTransform="uppercase"
      >
        Bonjour tout le monde, je m'appelle Finaritra Andrianiaina
      </Text>
      <Heading
        size={"xl"}
        as="h1"
        textTransform="uppercase"
        textAlign="justify"
      >
        Je suis passionné de programmation 💻, de jeux vidéos 🎮 et de voyage
        🏃‍♂⛺.
      </Heading>
      <Text fontSize={["sm", "md"]} textAlign="center" pt={2}>
        Vous êtes sur mon site web personnel construit avec nextjs.
      </Text>
    </>
  );
};

const Home = (props: { introduction: any; posts: PostData[] }) => {
  useEffect(() => {
    const script = createScript("/js/slick-carousel.js");
    document.body.appendChild(script);
    return () => {
      document.body.removeChild(script);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        as="header"
        height="calc( 100vh - 70px )"
        flexDirection="column"
        alignItems="center"
        justifyContent="space-around"
      >
        <Box width={["100%", "50%"]} px={[5, 0]}>
          <Header />
        </Box>
      </Flex>
      <Divider />
      <Container maxW="container.xl">
        <Markdown md={props.introduction} />
      </Container>
      <Divider mt="5" />
      <Container maxW="container.xl">
        <Heading p="3">Articles</Heading>
        <Box id="blog-list">
          {props.posts.map((v, index) => (
            <Box my="2" mx="2" key={index + "-card"}>
              <BlogCard {...v.meta} />
            </Box>
          ))}
        </Box>
      </Container>
      <Profile />
    </>
  );
};

export const getStaticProps = async () => {
  const { content } = await loadMarkdownFile("introduction.mdx");
  const posts = await loadBlogPosts();
  console.log(`posts.length`, posts.length);
  const introduction = await serialize(content);
  return { props: { introduction, posts } };
};

export default Home;
